name: example
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder:
    git:
      url: https://github.com/khirsig/flutter_form_builder
      ref: clearButton
  flutter_localizations:
    sdk: flutter
  form_builder_extra_fields:
    path: ../
  form_builder_validators: ^9.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
